title: RedPower - make TEAMSPEAK GREAT again
description: >-
  Najlepszy serwer TeamSpeak na Śląsku!
  Lepszy niż gorzoła twoich szwigrów!
  Zaproś swoja czelodka - RedPower.me
altname: RedPower - TeamSpeak3
author: ScooredMars
url: "https://redpower.me"


markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

plugins:
  - jekyll-press

jekyll-press:
  exclude: [ 'robots.txt' ]
  js_options: {}
  css_options: {}
  html_options: {}
