title: Projekty szkolne
description: Zbiór zadań szkolnych.
altname: School projects
author: ScooredMars
url: "https://dev.redpower.me"

email: admin@redpower.me

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

plugins:
  - jekyll-press

jekyll-press:
  exclude: [ 'robots.txt' ]
  js_options: {}
  css_options: {}
  html_options: {}
